# Generated by Django 5.2.3 on 2025-06-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Um usuário com esse e-mail já existe.'}, max_length=254, unique=True),
        ),
    ]
