# Generated by Django 5.2.3 on 2025-07-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='escuro', max_length=10),
        ),
    ]
