# Generated by Django 5.2.3 on 2025-07-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_perfil_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='assinatura_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='redes_sociais',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
