# Generated by Django 5.2.3 on 2025-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_perfil_assinatura_url_alter_perfil_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='redes_sociais',
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
