# Generated by Django 5.2.3 on 2025-07-19 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='postagens_curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
